### ISSUE TITLE
MotoGP Calendars won't import into O365

### ISSUE THREAD

**Issue by iMiMx** [nixxo/nixxo.github.io#2]
Many thanks for taking the time to put together the MotoGP calendars.

In the last year, I've migrated my email to O365 - unfortunately the ICS files will not import, either via HTTP/HTTPS or a download/upload.  I'd prefer to use an HTTP/HTTPS import, so that it updates automatically if there are races changes.

<Edited to remove red herrings> 

Logging this for reference/others, will take a look and see what needs to change to support O365 calendars.

**Comment by iMiMx** [comment]
Found this, in ICS-PY github

https://github.com/ics-py/ics-py/issues/389

If remove all occurrences of

`RRULE:FREQ=YEARLY;COUNT=1`

...from the downloaded ICS, then it works.

**Comment by nixxo** [comment]
This weekend I'll give it a look, thanks for reporting

**Comment by nixxo** [comment]
hi, I implemented the solution you linked and for now I applied it to the worldsbk calendars.

Can you give me a feedback if now the calendar is importable without issues in O365?

If that's the case I'll proceed in making the fix also for the motogp various calendars.

**Comment by iMiMx** [comment]
Much obliged - tested with the below, using a web/URL import, all good:

https://nixxo.github.io/calendars/wsbk/2024/WorldSBK_2024_calendar.ics

**Comment by nixxo** [comment]
I'll update the other calendars as well.
